# Default values for prism.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
api:
  repository: registry-helse.nhn.no/jonasbg/prism/api
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
  deployment: statefulSet
  mounts:
  - name: config
    mountPath: /config
    fromSecret: api-config-secret
    readOnly: true
  - name: data #create a PVC and PV when fromSecret, or fromConfig or inMemory is not present
    mountPath: /data
    readOnly: false
    storage: 10Gi
  - name: tmp #create a PVC and PV when fromSecret, or fromConfig or inMemory is not present
    inMemory: true
    mountPath: /tmp
    readOnly: false
    storage: 50Mi
  - name: config-web
    mountPath: /var/config/slack.json
    readOnly: true
    subPath: slack.json
    config:
      fileName: slack.json
      data: |
        { "blocks": [
          {
            "type": "section",
            "text": {
              "type": "mrkdwn",
              "text": "New vulnerability reported by *<@{{.FoundBy}}>*"
            }
          },
          {
            "type": "section",
            "text": {
              "type": "mrkdwn",
              "text": "*Title:* \n{{.Vulnerability.Title}}\n\n*Criticality:*\n{{.Vulnerability.Criticality}}\n\n*Category:*\n{{.Vulnerability.Category}}"
            },
            "accessory": {
              "type": "image",
              "image_url": "{{.ImageUrl}}",
              "alt_text": "{{.Vulnerability.Criticality}}"
            }
          },
          {
            "type": "section",
            "text": {
              "type": "mrkdwn",
              "text": "<{{.URL}}|More info>"
            }
          }]
        }
  env:
  - name: CONFIG_PATH
    value: "/config/config.yaml"
  - name: SLACK_PATH
    value: "/var/config/slack.json"
  services:
  - name: api
    port: 8080
  - name: healthz
    port: 8888

web:
  repository: registry-helse.nhn.no/jonasbg/prism/web
  pullPolicy: Always
  deployment: deployment
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
  host: prism.t-jonas-001.trd1-sky-test.sky.nhn.no
  hostRule:
    datascripts:
      - expose-nhn-office-client
      - expose-nhn-office-devops
      - expose-nhn-office-nat
      - expose-nhn-office-isp
      - bottom-deny-rule
  mounts:
  - name: temp
    mountPath: /tmp
    inMemory: true
    readOnly: false
    storage: 64Mi
  - name: config-web
    mountPath: /usr/share/nginx/html/.well-known/config.json
    readOnly: true
    subPath: config.json
    config:
      fileName: config.json
      data: |
        {
          "apiEndpoint": "https://prism.t-jonas-001.trd1-sky-test.sky.nhn.no"
        }
  services:
  - name: web
    port: 8080
