# Default values for prism.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
api:
  repository: registry-helse.nhn.no/jonasbg/prism/api
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
  deployment: statefulSet
  mounts:
  - name: config
    mountPath: /config
    fromSecret: api-config-secret
    readOnly: true
  - name: data #create a PVC and PV when fromSecret, or fromConfig or inMemory is not present
    mountPath: /data
    readOnly: false
    storage: 10Gi
  - name: tmp #create a PVC and PV when fromSecret, or fromConfig or inMemory is not present
    inMemory: true
    mountPath: /tmp
    readOnly: false
    storage: 50Mi
  - name: config-api
    mountPath: /var/config
    readOnly: true
    subPath: slack.json
    config:
      fileName: slack.json
      data: |
        { "blocks": [
          {
            "type": "section",
            "text": {
              "type": "mrkdwn",
              "text": "New vulnerability reported by *<@{{.FoundBy}}>*"
            }
          },
          {
            "type": "section",
            "text": {
              "type": "mrkdwn",
              "text": "*Title:* \n{{.Vulnerability.Title}}\n\n*Criticality:*\n{{.Vulnerability.Criticality}}\n\n*Category:*\n{{.Vulnerability.Category}}"
            },
            "accessory": {
              "type": "image",
              "image_url": "{{.ImageUrl}}",
              "alt_text": "{{.Vulnerability.Criticality}}"
            }
          },
          {
            "type": "section",
            "text": {
              "type": "mrkdwn",
              "text": "<{{.URL}}|More info>"
            }
          }]
        }
  env:
  - name: CONFIG_PATH
    value: "/config/config.yaml"
  - name: SLACK_PATH
    value: "/var/config/slack.json"
  services:
  - name: api
    port: 8080
  - name: healthz
    port: 8888

web:
  repository: registry-helse.nhn.no/jonasbg/prism/web
  pullPolicy: IfNotPresent
  deployment: deployment
  replicaCount: 2
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
  host: prism.t-jonas-001.trd1-sky-test.sky.nhn.no
  hostRule:
    datascripts:
      - expose-nhn-office-client
      - expose-nhn-office-devops
      - expose-nhn-office-nat
      - expose-nhn-office-isp
      - bottom-deny-rule
  mounts:
  - name: temp
    mountPath: /tmp
    inMemory: true
    readOnly: false
    storage: 64Mi
  - name: config-web
    mountPath: /usr/share/nginx/html/.well-known/config.json
    readOnly: true
    subPath: config.json
    config:
      fileName: config.json
      data: |
        {
          "apiEndpoint": "https://prism.t-jonas-001.trd1-sky-test.sky.nhn.no"
        }
    - name: nginx-config
      mountPath: etc/nginx/conf.d/default.conf
      readOnly: true
      subPath: default.conf
      config:
        fileName: default.conf
        data: |
          server {
              listen 8080;
              server_name localhost;
              root /usr/share/nginx/html;
              index index.html;

              # Add Content Security Policy
              add_header Content-Security-Policy "
                  default-src 'self' 'unsafe-inline' helsegitlab.nhn.no htsecure.gravatar.com/;
                  script-src 'self' 'unsafe-inline';
                  connect-src 'self';
                  style-src 'self' 'unsafe-inline';
                  img-src 'self' data: helsegitlab.nhn.no secure.gravatar.com/;
                  font-src 'self';
                  object-src 'none';
                  frame-src 'self';
                  media-src 'self';
                  child-src 'self';
                  worker-src 'self';
                  manifest-src 'self';
                  form-action 'self';
                  frame-ancestors 'self';
                  base-uri 'self';
                  require-sri-for script style;
                  upgrade-insecure-requests;
              ";

              location / {
                  try_files $uri $uri/ /index.html;
              }

              location ~* ^/.well-known/(CHANGELOG\.md|buildinfo\.json)$ {
                  add_header Cache-Control "no-cache, no-store, must-revalidate";
                  add_header Pragma "no-cache";
                  add_header Expires 0;
              }

              error_page 500 502 503 504 /50x.html;
              location = /50x.html {
                  root /usr/share/nginx/html;
              }
          }
  services:
  - name: web
    port: 8080
