# Default values for prism.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: github.com/NorskHelsenett/prism
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

prism:
  ingress:
    enabled: true
    host: prism.example.com
    className: ""
    annotations: {}
    tls: true
  storageClassName: ""
  serviceType: ClusterIP
  mounts:
  - name: config
    mountPath: /config
    fromSecret: api-config-secret
    readOnly: true
  - name: data
    mountPath: /data
    readOnly: false
    storage: 10Gi
    statefulSet: true
  - name: tmp
    inMemory: true
    mountPath: /tmp
    readOnly: false
    storage: 50Mi
  - name: config-slack
    mountPath: /var/config
    readOnly: true
    subPath: slack.json
    config:
      fileName: slack.json
      data: |
        { "blocks": [
          {
            "type": "section",
            "text": {
              "type": "mrkdwn",
              "text": "New vulnerability reported by *<@{{.FoundBy}}>*"
            }
          },
          {
            "type": "section",
            "text": {
              "type": "mrkdwn",
              "text": "*Criticality:*\n{{.Vulnerability.Criticality}}\n\n*Category:*\n{{.Vulnerability.Category}}"
            },
            "accessory": {
              "type": "image",
              "image_url": "{{.ImageUrl}}",
              "alt_text": "{{.Vulnerability.Criticality}}"
            }
          },
          {
            "type": "section",
            "text": {
              "type": "mrkdwn",
              "text": "<{{.URL}}|More info>"
            }
          }]
        }
  env:
  - name: CONFIG_PATH
    value: "/config/config.yaml"
  - name: SLACK_PATH
    value: "/var/config/slack.json"
  services:
  - name: http
    port: 8080
  - name: healthz
    port: 8888
    internal: true
  livenessProbe:
    httpGet:
      path: /healthz
      port: healthz
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
  readinessProbe:
    httpGet:
      path: /healthz
      port: healthz
    initialDelaySeconds: 10
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 3
  startupProbe:
    httpGet:
      path: /healthz
      port: healthz
    initialDelaySeconds: 0
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 30
