image: ubuntu:latest

variables:
  GITLAB_REGISTRY: "registry-helse.nhn.no/jonasbg/prism"
  DOCKER_CONFIG: $PWD/.kaniko/config.json

stages:
  - build
  - deploy

.template: &build_template
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
    - echo $PWD
    - mkdir -p $PWD/.kaniko/
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n $CI_REGISTRY_USER:$CI_REGISTRY_PASSWORD | base64)\"}}}" > $PWD/.kaniko/config.json
  script: |
    IMAGE="$GITLAB_REGISTRY/$IMAGE_REPOSITORY"
    DESTINATION="--destination $IMAGE:latest --destination $IMAGE:$(date '+%Y%m%d')"

    echo $DESTINATION

    /kaniko/executor \
      --context $CONTEXT_DIR \
      --dockerfile Dockerfile \
      --digest-file /tmp/digest \
      --image-name-with-digest-file /tmp/digest-name \
      --label "build.buildnumber=$CI_JOB_ID" \
      --label "build.builduri=$CI_PIPELINE_URL" \
      --label "build.project.uri=$CI_PROJECT_URL" \
      --label "build.project.name=$CI_PROJECT_PATH" \
      --label "build.repository.name=$CI_PROJECT_NAME" \
      --label "build.repository.branch=$CI_COMMIT_BRANCH" \
      --label "build.repository.commithash=$CI_COMMIT_SHA" \
      --label "maintainer=Jonas Bo Grimsgaard @ NHN <sikkerhet@nhn.no>" \
      --cache=true \
      --reproducible \
      --single-snapshot \
      $DESTINATION

    echo "DIGEST=$(cat /tmp/digest)" >> build.env
  artifacts:
    reports:
      dotenv: build.env


build-api:
  <<: *build_template
  variables:
    IMAGE_REPOSITORY: "api"
    CONTEXT_DIR: "api/"

build-web:
  <<: *build_template
  variables:
    IMAGE_REPOSITORY: "web"
    CONTEXT_DIR: "web/"

deploy-api:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  script:
    - echo "Deploying using API image digest $DIGEST"
  dependencies:
    - build-api

deploy-web:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  script:
    - echo "Deploying using API image digest $DIGEST"
  dependencies:
    - build-web