image: ubuntu:latest

variables:
  GITLAB_REGISTRY: "registry-helse.nhn.no/jonasbg/prism"
  DOCKER_CONFIG: $PWD/.kaniko/config.json

stages:
  - build
  - deploy

.template: &build_template
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
    - echo $PWD
    - mkdir -p $PWD/.kaniko/
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n $CI_REGISTRY_USER:$CI_REGISTRY_PASSWORD | base64)\"}}}" > $PWD/.kaniko/config.json
  script: |
    IMAGE="$GITLAB_REGISTRY/$IMAGE_REPOSITORY"
    DESTINATION="--destination $IMAGE:latest --destination $IMAGE:$(date '+%Y%m%d')"

    echo $DESTINATION

    /kaniko/executor \
      --context $CONTEXT_DIR \
      --dockerfile Dockerfile \
      --digest-file /tmp/digest \
      --image-name-with-digest-file /tmp/digest-name \
      --label "build.buildnumber=$CI_JOB_ID" \
      --label "build.builduri=$CI_PIPELINE_URL" \
      --label "build.project.uri=$CI_PROJECT_URL" \
      --label "build.project.name=$CI_PROJECT_PATH" \
      --label "build.repository.name=$CI_PROJECT_NAME" \
      --label "build.repository.branch=$CI_COMMIT_BRANCH" \
      --label "build.repository.commithash=$CI_COMMIT_SHA" \
      --label "maintainer=Jonas Bo Grimsgaard @ NHN <sikkerhet@nhn.no>" \
      --cache=true \
      --reproducible \
      --single-snapshot \
      $DESTINATION

    echo "DIGEST=$(cat /tmp/digest)" >> build.env
  artifacts:
    reports:
      dotenv: build.env

build-api:
  <<: *build_template
  variables:
    IMAGE_REPOSITORY: "api"
    CONTEXT_DIR: "api/"

build-web:
  <<: *build_template
  variables:
    IMAGE_REPOSITORY: "web"
    CONTEXT_DIR: "web/"

deploy-api:
  stage: deploy
  script:
    - echo "Deploying using API image digest $DIGEST"
    - echo "API_DIGEST=$DIGEST" >> build.env
  artifacts:
    reports:
      dotenv: build.env
  needs:
    - build-api
  dependencies:
    - build-api

deploy-web:
  stage: deploy
  script:
    - echo "Deploying using API image digest $DIGEST"
    - echo "WEB_DIGEST=$DIGEST" >> build.env
  artifacts:
    reports:
      dotenv: build.env
  needs:
    - build-web
  dependencies:
    - build-web

helm-push:
  stage: deploy
  image: ncr.sky.nhn.no/nhn/ci-deploy:0.0.2
  script: |
    echo $CI_REGISTRY_PASSWORD | helm registry login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    helm pull oci://$CI_REGISTRY/jonasbg/prism/helm/prism
    file=$(ls prism-*.tgz)
    CURRENT_VERSION=$(echo $file | sed 's/prism-\([0-9]\+\.[0-9]\+\.[0-9]\+\).tgz/\1/')
    export NEW_VERSION=$(echo $CURRENT_VERSION | awk -F. '{print $1"."$2"."$3+1}')
    echo "NEW VERSION" $NEW_VERSION
    yq e -i '.version = strenv(NEW_VERSION),.appVersion = strenv(APP_VERSION)' $CHART_DIR/Chart.yaml

    export API_TAG="$(date '+%Y%m%d')@$API_DIGEST"
    yq e -i '.api.tag = strenv(API_TAG)' $CHART_DIR/values.yaml

    export WEB_TAG="$(date '+%Y%m%d')@$WEB_DIGEST"
    yq e -i '.web.tag = strenv(WEB_TAG)' $CHART_DIR/values.yaml

    helm package $CHART_DIR
    helm push "${CHART_NAME}-${NEW_VERSION}.tgz" oci://$CI_REGISTRY/jonasbg/prism/helm
  variables:
    CHART_NAME: "prism"
    CHART_DIR: ".cluster/prism"
    APP_VERSION: "0.0.1"
  dependencies:
    - deploy-web
    - deploy-api
  needs:
    - deploy-web
    - deploy-api
  rules:
  - if: $CI_COMMIT_BRANCH == "main"