{{- range $key, $value := .Values }}
{{- if eq $value.deployment "deployment" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $key }}
  labels:
    app: {{ $key }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $key }}
  template:
    metadata:
      labels:
        app: {{ $key }}
    spec:
      automountServiceToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: {{ $key }}
        image: {{ $value.repository }}:{{ $value.tag | default "latest" }}
        imagePullPolicy: {{ $value.pullPolicy }}
        ports:
        {{- range $value.services }}
        - name: {{ .name }}
          containerPort: {{ .port }}
        {{- end }}
        env:
        {{- range $value.env }}
        - name: {{ .name }}
          value: {{ .value }}
        {{- end }}
        volumeMounts:
        {{- range $value.mounts }}
        - name: {{ .name }}
          mountPath: {{ .mountPath }}
          readOnly: {{ .readOnly | default false }}
        {{- end }}
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
              - ALL
      volumes:
      {{- range $value.mounts }}
      - name: {{ .name }}
        {{- if .fromSecret }}
        secret:
          secretName: {{ .fromSecret }}
        {{- else if .inMemory }}
        emptyDir:
          medium: Memory
          sizeLimit: {{ .storage | default "64Mi" }}
        {{- else if .config}}
        configMap:
          name: {{ .name }}
        {{- else }}
        persistentVolumeClaim:
          claimName: {{ $key }}-{{ .name }}-pvc
        {{- end }}
      {{- end }}
---
{{- end }}
{{- end }}