{{- with .Values.prism.hostRule }}
apiVersion: ako.vmware.com/v1alpha1
kind: HostRule
metadata:
  name: {{ $.Chart.Name }}-hostrule
spec:
  virtualhost:
    fqdn: {{ $.Values.prism.ingress.host }}
    datascripts: {{ toYaml .datascripts | nindent 6 }}
---
{{- end }}