{{- with .Values.app.hostRule }}
apiVersion: ako.vmware.com/v1alpha1
kind: HostRule
metadata:
  name: {{ $.Chart.Name }}-{{ $.Values.app.name }}-hostrule
spec:
  virtualhost:
    fqdn: {{ $.Values.app.host }}
    datascripts: {{ toYaml .datascripts | nindent 6 }}
---
{{- end }}