{{- with .Values.app.host }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $.Values.app.name }}-ingress
  {{- if $.Values.app.ingressAnnotations }}
  annotations:
    {{- toYaml $.Values.app.ingressAnnotations | nindent 4 }}
  {{- end }}
spec:
  {{- if $.Values.app.ingressClassName }}
  ingressClassName: {{ $.Values.app.ingressClassName }}
  {{- end }}
  tls:
  - hosts:
    - {{ . }}
    secretName: {{ $.Values.app.name }}-tls-secret
  rules:
  - host: {{ . }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ $.Values.app.name }}-service
            port:
              number: 8080
---
{{- end }}