apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $.Values.app.name }}
  labels:
    app: {{ $.Values.app.name }}
spec:
  serviceName: "{{ $.Values.app.name }}"
  replicas: {{ .Values.app.replicaCount | default 1}}
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      automountServiceAccountToken: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        supplementalGroups:
          - 100
        runAsNonRoot: true
        runAsUser: 101
        fsGroup: 101
      containers:
      - name: {{ $.Values.app.name }}
        image: {{ $.Values.image.repository }}:{{ $.Values.image.tag | default "latest" }}
        resources:
          {{- if .Values.app.resources }}
          {{- toYaml .Values.app.resources | nindent 10 }}
          {{- else }}
          requests:
            memory: "256Mi"  # Request 256 MiB of memory
            cpu: "250m"      # Request 250 millicpu (0.25 CPU cores)
          limits:
            memory: "2Gi"    # Limit to 2 GiB of memory
            cpu: "4"         # Limit to 4 CPU cores
          {{- end }}
        imagePullPolicy: {{ $.Values.image.pullPolicy }}
        ports:
        {{- range .Values.app.services }}
        - name: {{ .name }}
          containerPort: {{ .port }}
        {{- end }}
        env:
        {{- range .Values.app.env }}
        - name: {{ .name }}
          value: {{ .value }}
        {{- end }}
        {{- if .Values.app.livenessProbe }}
        livenessProbe:
          {{- toYaml .Values.app.livenessProbe | nindent 10 }}
        {{- end }}
        {{- if .Values.app.readinessProbe }}
        readinessProbe:
          {{- toYaml .Values.app.readinessProbe | nindent 10 }}
        {{- end }}
        {{- if .Values.app.startupProbe }}
        startupProbe:
          {{- toYaml .Values.app.startupProbe | nindent 10 }}
        {{- end }}
        volumeMounts:
        {{- range .Values.app.mounts }}
        - name: {{ .name }}
          mountPath: {{ .mountPath }}
          readOnly: {{ .readOnly | default false }}
        {{- end }}
        securityContext:
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
          privileged: false
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 101
          runAsGroup: 101
          readOnlyRootFilesystem: true
      volumes:
      {{- range .Values.app.mounts }}
      {{- if or .fromSecret .inMemory .config }}
      - name: {{ .name }}
        {{- if .fromSecret }}
        secret:
          secretName: {{ .fromSecret }}
        {{- else if .inMemory }}
        emptyDir:
          medium: Memory
          sizeLimit: {{ .storage | default "64Mi" }}
        {{- else if .config }}
        configMap:
          name: {{ .name }}
        {{- end }}
      {{- end }}
      {{- end }}
  volumeClaimTemplates:
  {{- range .Values.app.mounts }}
  {{- if not (or .fromSecret .inMemory .config) }}
  - metadata:
      name: {{ .name }}
    spec:
      accessModes: [ "ReadWriteOnce" ]
      {{- if $.Values.app.storageClassName }}
      storageClassName: {{ $.Values.app.storageClassName }}
      {{- end }}
      resources:
        requests:
          storage: {{ .storage | default "1Gi" }}
  {{- end }}
  {{- end }}