apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  serviceName: "{{ .Chart.Name }}"
  replicas: {{ .Values.prism.replicaCount | default 1}}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      automountServiceAccountToken: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        supplementalGroups:
          - 100
        runAsNonRoot: true
        runAsUser: 101
        fsGroup: 101
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}
        resources:
          {{- if .Values.prism.resources }}
          {{- toYaml .Values.prism.resources | nindent 10 }}
          {{- else }}
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "4"
          {{- end }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 8080
        - name: healthz
          containerPort: 8888
        env:
        - name: CONFIG_PATH
          value: "/config/config.yaml"
        {{- with .Values.prism.env }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        livenessProbe:
          {{- if .Values.prism.livenessProbe }}
          {{- toYaml .Values.prism.livenessProbe | nindent 10 }}
          {{- else }}
          httpGet:
            path: /healthz
            port: healthz
          initialDelaySeconds: 30
          periodSeconds: 10
          {{- end }}
        readinessProbe:
          {{- if .Values.prism.readinessProbe }}
          {{- toYaml .Values.prism.readinessProbe | nindent 10 }}
          {{- else }}
          httpGet:
            path: /healthz
            port: healthz
          initialDelaySeconds: 10
          periodSeconds: 5
          {{- end }}
        startupProbe:
          {{- if .Values.prism.startupProbe }}
          {{- toYaml .Values.prism.startupProbe | nindent 10 }}
          {{- else }}
          httpGet:
            path: /healthz
            port: healthz
          periodSeconds: 5
          failureThreshold: 30
          {{- end }}
        volumeMounts:
        {{- range .Values.prism.mounts }}
        - name: {{ .name }}
          mountPath: {{ .mountPath }}
          {{- if .subPath }}
          subPath: {{ .subPath }}
          {{- end }}
          readOnly: {{ .readOnly | default false }}
        {{- end }}
        securityContext:
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
          privileged: false
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 101
          runAsGroup: 101
          readOnlyRootFilesystem: true
      volumes:
      {{- range .Values.prism.mounts }}
      {{- if or .fromSecret .inMemory .config }}
      - name: {{ .name }}
        {{- if .fromSecret }}
        secret:
          secretName: {{ .fromSecret }}
        {{- else if .inMemory }}
        emptyDir:
          medium: Memory
          sizeLimit: {{ .storage | default "64Mi" }}
        {{- else if .config }}
        configMap:
          name: {{ .name }}
        {{- end }}
      {{- end }}
      {{- end }}
  volumeClaimTemplates:
  {{- range .Values.prism.mounts }}
  {{- if not (or .fromSecret .inMemory .config) }}
  - metadata:
      name: {{ .name }}
    spec:
      accessModes: [ "ReadWriteOnce" ]
      {{- if $.Values.prism.storageClassName }}
      storageClassName: {{ $.Values.prism.storageClassName }}
      {{- end }}
      resources:
        requests:
          storage: {{ .storage | default "1Gi" }}
  {{- end }}
  {{- end }}