oidc:
  clientID: ""
  clientSecret: ""
  redirectUri: "http://localhost:8080/api/callback"
  providerUri: ""
cors:
  origin: "http://localhost:5173"
admins:
  - example@email.com
database:
  path: "./tmp"
events:
  interval: 10
slack:
  token: ""
  webhookUrl: ""
