oidc:
  gitlab:
    clientID: ""
    clientSecret: ""
    redirectUri: "http://localhost:5173/api/callback"
    providerUri: ""
  github:
    clientID: ""
    clientSecret: ""
    redirectUri: "http://localhost:5173/api/callback"
    providerUri: ""
cors:
  origin: "http://localhost:5173"
admins:
  - example@email.com
database:
  path: ".tmp/"
events:
  interval: 10
slack:
  token: ""
  webhookUrl: ""
secrets:
  HMAC_SECRET_KEY: "DO_NOT_LET_ME_CATCH_YOU_USING_THIS_IN_PROD"
